apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automobile.fullname" . }}-db-config
  labels:
    {{- include "automobile.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.database.config.url | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automobile.fullname" . }}-frontend-config
  labels:
    {{- include "automobile.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_BASE_URL: {{ .Values.frontend.baseUrl | quote }}


