apiVersion: v1
kind: Secret
metadata:
  name: {{ include "automobile.fullname" . }}-db-secret
  labels:
    {{- include "automobile.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.secret.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.secret.password | quote }}

